# Generated by Django 5.1.3 on 2024-11-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_color',
            field=models.CharField(default='#000', max_length=7),
        ),
    ]
