# Generated by Django 5.1.3 on 2024-11-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_user_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user_color',
        ),
    ]
